"""empty message

Revision ID: 2bcb20b9da5e
Revises: 6c87fd17d55e
Create Date: 2016-06-23 14:10:40.114505

"""

# revision identifiers, used by Alembic.
revision = '2bcb20b9da5e'
down_revision = '6c87fd17d55e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codingsessionusers', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('codingsessionusers', sa.Column('user_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codingsessionusers', 'user_name')
    op.drop_column('codingsessionusers', 'user_email')
    ### end Alembic commands ###
