"""empty message

Revision ID: 6781cca5ab99
Create Date: 2016-06-22 15:46:32.970939

"""

# revision identifiers, used by Alembic.
revision = '6781cca5ab99'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    '''
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_ip', sa.String(length=45), nullable=True))
    op.add_column(u'user', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column(u'user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column(u'user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column(u'user', 'authenticated')
    op.drop_column(u'user', 'name')
    op.drop_column(u'user', 'google_id')
    op.drop_column(u'user', 'login_token')
    op.drop_column(u'user', 'avatar')
    op.drop_column(u'user', 'user_id')'''
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    '''
    op.add_column(u'user', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column(u'user', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('login_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'login_count')
    op.drop_column(u'user', 'last_login_ip')
    op.drop_column(u'user', 'last_login_at')
    op.drop_column(u'user', 'id')
    op.drop_column(u'user', 'full_name')
    op.drop_column(u'user', 'current_login_ip')
    op.drop_column(u'user', 'current_login_at')
    op.drop_column(u'user', 'confirmed_at')
    op.drop_column(u'user', 'active')
    op.drop_table('roles_users')
    op.drop_table('role')'''
    ### end Alembic commands ###
    pass
