"""empty message

Revision ID: 6c87fd17d55e
Revises: a7f94e009dfd
Create Date: 2016-06-23 11:42:51.978399

"""

# revision identifiers, used by Alembic.
revision = '6c87fd17d55e'
down_revision = 'a7f94e009dfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codingsessionusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['codesessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codingsessionusers')
    ### end Alembic commands ###
