"""empty message

Revision ID: 83c02e6ff58d
Revises: 37fa830b5b04
Create Date: 2016-06-21 18:59:02.543864

"""

# revision identifiers, used by Alembic.
revision = '83c02e6ff58d'
down_revision = '37fa830b5b04'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
