"""empty message

Revision ID: a7f94e009dfd
Revises: ef4ae44d1920
Create Date: 2016-06-23 07:54:45.829702

"""

# revision identifiers, used by Alembic.
revision = 'a7f94e009dfd'
down_revision = 'ef4ae44d1920'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currentusersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['codesessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currentusersession')
    ### end Alembic commands ###
