"""empty message

Revision ID: ef4ae44d1920
Revises: 512c453f9e66
Create Date: 2016-06-22 18:29:57.707110

"""

# revision identifiers, used by Alembic.
revision = 'ef4ae44d1920'
down_revision = '512c453f9e66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codesessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_owner', sa.String(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('session_desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codesessions')
    ### end Alembic commands ###
